<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- This report is to record the items that are reported FOUND to the Lost and Found Station -->

<!-- Link to XSL -->
<?xml-stylesheet type="text/xsl" href="ItemTobeClaimed.xsl" ?>

<!-- Internal DTD -->
<!DOCTYPE foundReport [

<!ELEMENT foundReport (item*) >
<!ELEMENT item (status, description, report:datetime, found:datetime, claim:datetime, location, detail, reportBy, claimBy) >
<!ELEMENT status EMPTY >
<!ELEMENT description (#PCDATA) >
<!ELEMENT report:datetime (report:date, report:time) >
<!ELEMENT report:date EMPTY >
<!ELEMENT report:time EMPTY >
<!ELEMENT found:datetime (found:date, found:time) >
<!ELEMENT found:date EMPTY >
<!ELEMENT found:time EMPTY >
<!ELEMENT claim:datetime (claim:date, claim:time) >
<!ELEMENT claim:date EMPTY >
<!ELEMENT claim:time EMPTY >
<!ELEMENT location (#PCDATA) >
<!ELEMENT detail (#PCDATA) >
<!ELEMENT reportBy (name, email, phone, id) >
<!ELEMENT claimBy (itemLost, name, email, phone, id) >
<!ELEMENT name (firstName, lastName) >
<!ELEMENT firstName (#PCDATA) >
<!ELEMENT lastName (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT id (#PCDATA) >


<!ATTLIST item id ID #REQUIRED >
<!ATTLIST item include IDREFS #IMPLIED>
<!ATTLIST status choice (Open | Closed) #REQUIRED >
<!ATTLIST report:datetime xmlns:report CDATA #FIXED "http://www.w3.org/xml/report/">
<!ATTLIST report:date 
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST report:time 
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>

<!ATTLIST found:datetime xmlns:found CDATA #FIXED "http://www.w3.org/xml/found/">
<!ATTLIST found:date 
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST found:time 
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>

<!ATTLIST claim:datetime xmlns:claim CDATA #FIXED "http://www.w3.org/xml/claim/">
<!ATTLIST claim:date 
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST claim:time 
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>

]>

<foundReport>

  <item id="F2001"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Open" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>Watch</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="03" />
      <report:time hour="17" minute="26" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="03" />
      <found:time hour="17" minute="00" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="" month="" date="" />
      <claim:time hour="" minute="" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>MSMX2003</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    Model: GA-2000S-1A
    Colour: Black
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Chang He</firstName>
        <lastName>Wong</lastName>
      </name>
      <email>1151105293@student.mmu.edu.my</email>
      <phone>012-9161580</phone>
      <id>1151105293</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName></firstName>
        <lastName></lastName>
      </name>
      <email></email>
      <phone></phone>
      <id></id>
    </claimBy>
  </item>

  <item id="F2002" include="F2003"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Closed" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A book with the title, "Sapiens"</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="06" date="03" />
      <report:time hour="13" minute="21" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="06" date="03" />
      <found:time hour="14" minute="00" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="2019" month="06" date="04" />
      <claim:time hour="11" minute="12" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>One of the tables on second floor of the library besides a wireless keyboard</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    A book by Yuval Noah Harari.
    The owner's name is written on the cover of the book -- "Enzo Cheng". 
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Daphne</firstName>
        <lastName>Flower</lastName>
      </name>
      <email>Dflower@hotmail.com</email>
      <phone>012-9450002</phone>
      <id>1151103434</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
  
      <name>
        <firstName>Enzo</firstName>
        <lastName>Cheng</lastName>
      </name>
      <email>enzocheng977@hotmail.com</email>
      <phone>013-3333333</phone>
      <id>1151010001</id>
    </claimBy>
  </item>

  <item id="F2003"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Closed" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A wireless keyboard in black color was left on a table in Libaray. 
    A book was lying beside this keyboard.</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="10" />
      <report:time hour="21" minute="30" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="11" />
      <found:time hour="10" minute="20" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="" month="" date="" />
      <claim:time hour="" minute="" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>One of the tables on second floor of the library</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    An Alcatroz 2.4G wireless keyboard was left on one of the table in the new LP last night.
    Model: AirPad1
    Has a built-in touch pad
    ]]></detail>

       <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Daphne</firstName>
        <lastName>Flower</lastName>
      </name>
      <email>Dflower@hotmail.com</email>
      <phone>012-9450002</phone>
      <id>1151103434</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName>Enzo</firstName>
        <lastName>Cheng</lastName>
      </name>
      <email>enzocheng977@hotmail.com</email>
      <phone>013-3333333</phone>
      <id>1151010001</id>
    </claimBy>
  </item>

<item id="F2004"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Closed" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A silver scientific calculator with a name tag --"Andrew Wang 1131140099"</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="01" />
      <report:time hour="14" minute="21" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="01" />
      <found:time hour="16" minute="13" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="2019" month="07" date="01" />
      <claim:time hour="18" minute="00" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>One of the tables in new LP</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    A new scientic calculator with a name tag writting, "Andrew Wong 1131140099" 
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Kah Siang</firstName>
        <lastName>Koh</lastName>
      </name>
      <email>KS123@hotmail.com</email>
      <phone>012-9330002</phone>
      <id>1120010022</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName>Andrew</firstName>
        <lastName>Wang</lastName>
      </name>
      <email>wang8090@hotmail.com</email>
      <phone>013-3334443</phone>
      <id>1131140099</id>
    </claimBy>
  </item>

  <item id="F2005"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Open" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A brand new portable harddrive in blue color."</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="11" />
      <report:time hour="13" minute="30" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="11" />
      <found:time hour="15" minute="15" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="" month="" date="" />
      <claim:time hour="" minute="" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>In a CLC lecture hall, MSMX3016</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    An blue color Seagate portable harddirve was left on the lecturer's table in the lecture hall.  
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Elaine</firstName>
        <lastName>Cheng</lastName>
      </name>
      <email>1191191199@hotmail.com</email>
      <phone>014-3339983</phone>
      <id>1191191199</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName></firstName>
        <lastName></lastName>
      </name>
      <email></email>
      <phone></phone>
      <id></id>
    </claimBy>
  </item>

  <item id="F2006"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Closed" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>6 keys with a pink key ring.</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="15" />
      <report:time hour="11" minute="30" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="12" />
      <found:time hour="21" minute="15" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="2019" month="07" date="15" />
      <claim:time hour="12" minute="00" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>On the floor, beside a chair in gym room.</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    6 six keys chained by a pink key rings was left on the floor of the gym room.
    No name tag is chained with the keys.
    A tag stating --"B-11-03-03", is chained with the keychain ring.
    I suppose these are house keys.   
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Lillian</firstName>
        <lastName>Wong</lastName>
      </name>
      <email>1191220091@gmail.com</email>
      <phone>018-1113303</phone>
      <id>1191220091</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName>Joanna</firstName>
        <lastName>Johnson</lastName>
      </name>
      <email>joannaJohn344@outlook.com</email>
      <phone>011-9623335</phone>
      <id>1161107869</id>
    </claimBy>
  </item>

 <item id="F2007"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Closed" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A pair of stylish glasses with black color frame</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="15" />
      <report:time hour="15" minute="20" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="15" />
      <found:time hour="16" minute="00" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="2019" month="07" date="16" />
      <claim:time hour="09" minute="15" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>Found on a table of the Software Enginnering Lab, MNBR2007</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    A black frame, stylish pair of glasses. 
    The brand of the frame is called, "Whoosh".   
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Terrence</firstName>
        <lastName>Tam</lastName>
      </name>
      <email>1131188801@outlook.com</email>
      <phone>012-7747731</phone>
      <id>1131188801</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>
      <name>
        <firstName>Daphne</firstName>
        <lastName>Flower</lastName>
      </name>
      <email>Dflower@hotmail.com</email>
      <phone>012-9450002</phone>
      <id>1151103434</id>
    </claimBy>
  </item>

 <item id="F2008"> <!-- indicate an item that have been found; id incidate the primary key -->
    <status choice="Open" /> <!-- Open: Item is awaiting to be claimed; Closed: Item have been claimed -->
    <description>A platinum, heart shaped necklace</description> <!-- short description of the item found -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="17" />
      <report:time hour="12" minute="20" />
    </report:datetime>

    <!-- when the item is being found by the reporting person -->
    <found:datetime xmlns:found="http://www.w3.org/xml/found/">
      <found:date year="2019" month="07" date="17" />
      <found:time hour="12" minute="40" />
    </found:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="" month="" date="" />
      <claim:time hour="" minute="" />
    </claim:datetime>

    <!-- where the item is being found by the reporting person -->
    <location>On the sink of the ladies toilet, which was on the ground floor of CLC</location>

    <!-- detail description of the item found -->
    <detail> <![CDATA[
    A platinum, heart shaped necklace was left on the sink of the ladies toilet in CLC.
    The necklace is about 20cm long.      
    ]]></detail>

    <!-- item found is reported by this person -->
    <reportBy>
      <name>
        <firstName>Annebelle</firstName>
        <lastName>Ferryman</lastName>
      </name>
      <email>1172281100@gmail.com</email>
      <phone>014-9982234</phone>
      <id>1172281100</id>
    </reportBy>

    <!-- item is being claimed by this person -->
    <claimBy>]
      <name>
        <firstName></firstName>
        <lastName></lastName>
      </name>
      <email></email>
      <phone></phone>
      <id></id>
    </claimBy>
  </item>


</foundReport>
