=== ksk102/TCP3151_Assignment/Part1-Lost_Item_Reporting_System/LostItemReport.dtd
<!ELEMENT lostReport (item*) >
<!ELEMENT item (status, description, report:datetime, lost:datetime, claim:datetime, locations, detail, reportBy, returnBy) >
<!ELEMENT status EMPTY >
<!ELEMENT description (#PCDATA) >
<!ELEMENT report:datetime (report:date, report:time) >
<!ELEMENT report:date EMPTY >
<!ELEMENT report:time EMPTY >
<!ELEMENT lost:datetime (lost:dateFrom, lost:dateTo, lost:timeFrom, lost:timeTo) >
<!ELEMENT lost:dateFrom EMPTY >
<!ELEMENT lost:dateTo EMPTY >
<!ELEMENT lost:timeFrom EMPTY >
<!ELEMENT lost:timeTo EMPTY >
<!ELEMENT claim:datetime (claim:date, claim:time) >
<!ELEMENT claim:date EMPTY >
<!ELEMENT claim:time EMPTY >
<!ELEMENT locations (location+)>
<!ELEMENT location (#PCDATA) >
<!ELEMENT detail (#PCDATA) >
<!ELEMENT reportBy (name, email, phone, id) >
<!ELEMENT returnBy (name, email, phone, id) >
<!ELEMENT name (firstName, lastName) >
<!ELEMENT firstName (#PCDATA) >
<!ELEMENT lastName (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT id (#PCDATA) >

<!ATTLIST item id ID #REQUIRED >
<!ATTLIST item include IDREF #IMPLIED>
<!ATTLIST status choice (Open | Found | Closed) #REQUIRED >
<!ATTLIST report:datetime xmlns:report CDATA #FIXED "http://www.w3.org/xml/report/">
<!ATTLIST report:date 
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST report:time 
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>
<!ATTLIST lost:datetime xmlns:lost CDATA #FIXED "http://www.w3.org/xml/lost/">
<!ATTLIST lost:dateFrom
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST lost:dateTo
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST lost:timeFrom
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>
<!ATTLIST lost:timeTo
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>
<!ATTLIST claim:datetime xmlns:claim CDATA #FIXED "http://www.w3.org/xml/claim/">
<!ATTLIST claim:date 
  year CDATA #REQUIRED
  month CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ATTLIST claim:time 
  hour CDATA #REQUIRED
  minute CDATA #REQUIRED
>

=== ksk102/TCP3151_Assignment/Part1-Lost_Item_Reporting_System/LostItemReport.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- This report is to record the items that are reported LOST to the Lost and Found Station -->

<!-- External DTD -->
<!DOCTYPE lostReport SYSTEM "LostItemReport.dtd" >

<!-- Link to XSL -->
<?xml-stylesheet type="text/xsl" href="ListOfLostItem.xsl" ?>

<lostReport>
  <item id="L1001"> <!-- indicate an item that have been lost; id incidate the primary key -->
    <status choice="Open" /> <!-- Open: Item is awaiting to be found and returned; Found: Item have been found and awaiting to be returned; Closed: Item have been found and returned -->
    <description>Student ID</description> <!-- short description of the item lost -->

    <!-- when the item is reported to the lost and found station -->
    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="02" />
      <report:time hour="17" minute="26" />
    </report:datetime>

    <!-- when the item is suspected lost -->
    <lost:datetime xmlns:lost="http://www.w3.org/xml/lost/">
      <lost:dateFrom year="2019" month="07" date="02" />
      <lost:dateTo year="2019" month="07" date="02" />
      <lost:timeFrom hour="14" minute="00" />
      <lost:timeTo hour="16" minute="00" />
    </lost:datetime>

    <!-- when the item is being claimed by its owner -->
    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="" month="" date="" />
      <claim:time hour="" minute="" />
    </claim:datetime>

    <!-- where the item is suspected lost -->
    <location>MSMX0001</location>

    <!-- detail description of the item lost -->
    <detail> <![CDATA[
    Student Id: 1131119882
    ]]></detail>

    <!-- item lost is reported by this person -->
    <reportBy>
      <name>
        <firstName>Kah Siang</firstName>
        <lastName>Koh</lastName>
      </name>
      <email>kahsiang95@hotmail.com</email>
      <phone>0176815218</phone>
      <id>1131119882</id>
    </reportBy>

    <!-- item is being found by this person -->
    <returnBy>
      <name>
        <firstName></firstName>
        <lastName></lastName>
      </name>
      <email></email>
      <phone></phone>
      <id></id>
    </returnBy>
  </item>

  <item id="L1002">
    <status choice="Closed" />
    <description>Wallet</description>

    <report:datetime xmlns:report="http://www.w3.org/xml/report/">
      <report:date year="2019" month="07" date="03" />
      <report:time hour="11" minute="59" />
    </report:datetime>
		
    <lost:datetime xmlns:lost="http://www.w3.org/xml/lost/">
      <lost:dateFrom year="2019" month="07" date="03" />
      <lost:dateTo year="2019" month="07" date="03" />
      <lost:timeFrom hour="08" minute="00" />
      <lost:timeTo hour="11" minute="30" />
    </lost:datetime>

    <claim:datetime xmlns:claim="http://www.w3.org/xml/claim/">
      <claim:date year="2019" month="07" date="04" />
      <claim:time hour="08" minute="04" />
    </claim:datetime>

    <location>MSMX0001</location>

    <detail> <![CDATA[
    Black colour, around RM300 inside, include student id - 1151104900, ic - 980101-01-0001, driving license, and aeon member card
    ]]></detail>

    <reportBy>
      <name>
        <firstName>Kean Wah</firstName>
        <lastName>Cheng</lastName>
      </name>
      <email>1151104900@student.mmu.edu.my</email>
      <phone>0129350714</phone>
      <id>1151104900</id>
    </reportBy>

    <returnBy>
      <name>
        <firstName>Daphne</firstName>
        <lastName>Bunga Dwiputriane</lastName>
      </name>
      <email>1151105086@student.mmu.edu.my</email>
      <phone>017-6356898</phone>
      <id>1151105086</id>
    </returnBy>
  </item>
  
</lostReport>
